CREATE OR REPLACE FUNCTION "public"."insert_cabin_history"()
  RETURNS "pg_catalog"."trigger" AS $BODY$
BEGIN
    -- Check if the patient ID is updated to NULL
    IF OLD."PATIENT_ID" IS NOT NULL AND NEW."PATIENT_ID" IS NULL THEN
        INSERT INTO "CABIN_HISTORY" ("DATE", "CABIN_NO", "FLOOR_NO", "PATIENT_ID", "DOCTOR_ID_DAY", "DOCTOR_ID_NIGHT", "CABIN_TYPE", "NURSE_ID_1", "NURSE_ID_2")
        VALUES (CURRENT_DATE, OLD."CABIN_NO", OLD."FLOOR_NO", OLD."PATIENT_ID", OLD."DOCTOR_ID_DAY", OLD."DOCTOR_ID_NIGHT", OLD."CABIN_TYPE", OLD."NURSE_ID_1", OLD."NURSE_ID_2");
    END IF;
    RETURN NEW;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100

CREATE TRIGGER insert_cabin_history
AFTER UPDATE 
ON "CABIN"
FOR EACH ROW
EXECUTE FUNCTION "public"."insert_cabin_history"();
```
