CREATE OR REPLACE FUNCTION "public"."insert_billing_and_medical_record_data"()
  RETURNS "pg_catalog"."trigger" AS $BODY$
BEGIN
    DECLARE
        appointment_fee FLOAT;
    BEGIN
        INSERT INTO "BILLING" ("APPOINTMENT_ID", "DATE")
        VALUES (NEW."APPOINTMENT_ID", CURRENT_DATE);
        SELECT "APPOINTMENT_FEE" INTO appointment_fee
        FROM "DOCTORS"
        WHERE "DOCTOR_ID" = NEW."DOCTOR_ID";
        INSERT INTO "MEDICAL_RECORD_PATIENT" ("APPOINTMENT_ID", "DOCTOR_ID", "PATIENT_ID", "SERVICE_TYPE", "SERVICE_DATE")
        VALUES (NEW."APPOINTMENT_ID", NEW."DOCTOR_ID", NEW."PATIENT_ID", 'Appointment', NEW."APPOINTMENT_DATE");
        UPDATE "BILLING"
        SET "AMOUNT_DUE" = appointment_fee
        WHERE "APPOINTMENT_ID" = NEW."APPOINTMENT_ID";
        RETURN NEW;
    END;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100