UPDATE "WARD" 
SET "ADMISSION_REASON" = CASE 
    WHEN "BED_1" IS NOT NULL THEN
        CASE floor(random()*31)::int
            WHEN 0 THEN 'Fever'
            WHEN 1 THEN 'Influenza'
            WHEN 2 THEN 'Pneumonia'
            WHEN 3 THEN 'Appendicitis'
            WHEN 4 THEN 'Asthma'
            WHEN 5 THEN 'Diabetes'
            WHEN 6 THEN 'Hypertension'
            WHEN 7 THEN 'Arthritis'
            WHEN 8 THEN 'Migraine'
            WHEN 9 THEN 'COVID-19'
            WHEN 10 THEN 'Bronchitis'
            WHEN 11 THEN 'Gastritis'
            WHEN 12 THEN 'Ulcer'
            WHEN 13 THEN 'Kidney stones'
            WHEN 14 THEN 'Urinary tract infection'
            WHEN 15 THEN 'Conjunctivitis'
            WHEN 16 THEN 'Malaria'
            WHEN 17 THEN 'Cholera'
            WHEN 18 THEN 'Typhoid'
            WHEN 19 THEN 'Dengue fever'
            WHEN 20 THEN 'Measles'
            WHEN 21 THEN 'Chickenpox'
            WHEN 22 THEN 'Tuberculosis'
            WHEN 23 THEN 'Rheumatism'
            WHEN 24 THEN 'Eczema'
            WHEN 25 THEN 'Psoriasis'
            WHEN 26 THEN 'Meningitis'
            WHEN 27 THEN 'Hepatitis'
            WHEN 28 THEN 'Cancer'
            WHEN 29 THEN 'Stroke'
            WHEN 30 THEN 'Common Cold'
            ELSE 'Unknown'
        END
    WHEN "BED_2" IS NOT NULL THEN
        CASE floor(random()*31)::int
            WHEN 0 THEN 'Fever'
            WHEN 1 THEN 'Influenza'
            WHEN 2 THEN 'Pneumonia'
            WHEN 3 THEN 'Appendicitis'
            WHEN 4 THEN 'Asthma'
            WHEN 5 THEN 'Diabetes'
            WHEN 6 THEN 'Hypertension'
            WHEN 7 THEN 'Arthritis'
            WHEN 8 THEN 'Migraine'
            WHEN 9 THEN 'COVID-19'
            WHEN 10 THEN 'Bronchitis'
            WHEN 11 THEN 'Gastritis'
            WHEN 12 THEN 'Ulcer'
            WHEN 13 THEN 'Kidney stones'
            WHEN 14 THEN 'Urinary tract infection'
            WHEN 15 THEN 'Conjunctivitis'
            WHEN 16 THEN 'Malaria'
            WHEN 17 THEN 'Cholera'
            WHEN 18 THEN 'Typhoid'
            WHEN 19 THEN 'Dengue fever'
            WHEN 20 THEN 'Measles'
            WHEN 21 THEN 'Chickenpox'
            WHEN 22 THEN 'Tuberculosis'
            WHEN 23 THEN 'Rheumatism'
            WHEN 24 THEN 'Eczema'
            WHEN 25 THEN 'Psoriasis'
            WHEN 26 THEN 'Meningitis'
            WHEN 27 THEN 'Hepatitis'
            WHEN 28 THEN 'Cancer'
            WHEN 29 THEN 'Stroke'
            WHEN 30 THEN 'Common Cold'
            ELSE 'Unknown'
        END
    -- Continue for BED_3 to BED_10
    WHEN "BED_3" IS NOT NULL THEN
        CASE floor(random()*31)::int
            WHEN 0 THEN 'Fever'
            WHEN 1 THEN 'Influenza'
            WHEN 2 THEN 'Pneumonia'
            WHEN 3 THEN 'Appendicitis'
            WHEN 4 THEN 'Asthma'
            WHEN 5 THEN 'Diabetes'
            WHEN 6 THEN 'Hypertension'
            WHEN 7 THEN 'Arthritis'
            WHEN 8 THEN 'Migraine'
            WHEN 9 THEN 'COVID-19'
            WHEN 10 THEN 'Bronchitis'
            WHEN 11 THEN 'Gastritis'
            WHEN 12 THEN 'Ulcer'
            WHEN 13 THEN 'Kidney stones'
            WHEN 14 THEN 'Urinary tract infection'
            WHEN 15 THEN 'Conjunctivitis'
            WHEN 16 THEN 'Malaria'
            WHEN 17 THEN 'Cholera'
            WHEN 18 THEN 'Typhoid'
            WHEN 19 THEN 'Dengue fever'
            WHEN 20 THEN 'Measles'
            WHEN 21 THEN 'Chickenpox'
            WHEN 22 THEN 'Tuberculosis'
            WHEN 23 THEN 'Rheumatism'
            WHEN 24 THEN 'Eczema'
            WHEN 25 THEN 'Psoriasis'
            WHEN 26 THEN 'Meningitis'
            WHEN 27 THEN 'Hepatitis'
            WHEN 28 THEN 'Cancer'
            WHEN 29 THEN 'Stroke'
            WHEN 30 THEN 'Common Cold'
            ELSE 'Unknown'
        END
    WHEN "BED_4" IS NOT NULL THEN
        CASE floor(random()*31)::int
            WHEN 0 THEN 'Fever'
            WHEN 1 THEN 'Influenza'
            WHEN 2 THEN 'Pneumonia'
            WHEN 3 THEN 'Appendicitis'
            WHEN 4 THEN 'Asthma'
            WHEN 5 THEN 'Diabetes'
            WHEN 6 THEN 'Hypertension'
            WHEN 7 THEN 'Arthritis'
            WHEN 8 THEN 'Migraine'
            WHEN 9 THEN 'COVID-19'
            WHEN 10 THEN 'Bronchitis'
            WHEN 11 THEN 'Gastritis'
            WHEN 12 THEN 'Ulcer'
            WHEN 13 THEN 'Kidney stones'
            WHEN 14 THEN 'Urinary tract infection'
            WHEN 15 THEN 'Conjunctivitis'
            WHEN 16 THEN 'Malaria'
            WHEN 17 THEN 'Cholera'
            WHEN 18 THEN 'Typhoid'
            WHEN 19 THEN 'Dengue fever'
            WHEN 20 THEN 'Measles'
            WHEN 21 THEN 'Chickenpox'
            WHEN 22 THEN 'Tuberculosis'
            WHEN 23 THEN 'Rheumatism'
            WHEN 24 THEN 'Eczema'
            WHEN 25 THEN 'Psoriasis'
            WHEN 26 THEN 'Meningitis'
            WHEN 27 THEN 'Hepatitis'
            WHEN 28 THEN 'Cancer'
            WHEN 29 THEN 'Stroke'
            WHEN 30 THEN 'Common Cold'
            ELSE 'Unknown'
        END
    WHEN "BED_5" IS NOT NULL THEN
        CASE floor(random()*31)::int
            WHEN 0 THEN 'Fever'
            WHEN 1 THEN 'Influenza'
            WHEN 2 THEN 'Pneumonia'
            WHEN 3 THEN 'Appendicitis'
            WHEN 4 THEN 'Asthma'
            WHEN 5 THEN 'Diabetes'
            WHEN 6 THEN 'Hypertension'
            WHEN 7 THEN 'Arthritis'
            WHEN 8 THEN 'Migraine'
            WHEN 9 THEN 'COVID-19'
            WHEN 10 THEN 'Bronchitis'
            WHEN 11 THEN 'Gastritis'
            WHEN 12 THEN 'Ulcer'
            WHEN 13 THEN 'Kidney stones'
            WHEN 14 THEN 'Urinary tract infection'
            WHEN 15 THEN 'Conjunctivitis'
            WHEN 16 THEN 'Malaria'
            WHEN 17 THEN 'Cholera'
            WHEN 18 THEN 'Typhoid'
            WHEN 19 THEN 'Dengue fever'
            WHEN 20 THEN 'Measles'
            WHEN 21 THEN 'Chickenpox'
            WHEN 22 THEN 'Tuberculosis'
            WHEN 23 THEN 'Rheumatism'
            WHEN 24 THEN 'Eczema'
            WHEN 25 THEN 'Psoriasis'
            WHEN 26 THEN 'Meningitis'
            WHEN 27 THEN 'Hepatitis'
            WHEN 28 THEN 'Cancer'
            WHEN 29 THEN 'Stroke'
            WHEN 30 THEN 'Common Cold'
            ELSE 'Unknown'
        END
    WHEN "BED_6" IS NOT NULL THEN
        CASE floor(random()*31)::int
            WHEN 0 THEN 'Fever'
            WHEN 1 THEN 'Influenza'
            WHEN 2 THEN 'Pneumonia'
            WHEN 3 THEN 'Appendicitis'
            WHEN 4 THEN 'Asthma'
            WHEN 5 THEN 'Diabetes'
            WHEN 6 THEN 'Hypertension'
            WHEN 7 THEN 'Arthritis'
            WHEN 8 THEN 'Migraine'
            WHEN 9 THEN 'COVID-19'
            WHEN 10 THEN 'Bronchitis'
            WHEN 11 THEN 'Gastritis'
            WHEN 12 THEN 'Ulcer'
            WHEN 13 THEN 'Kidney stones'
            WHEN 14 THEN 'Urinary tract infection'
            WHEN 15 THEN 'Conjunctivitis'
            WHEN 16 THEN 'Malaria'
            WHEN 17 THEN 'Cholera'
            WHEN 18 THEN 'Typhoid'
            WHEN 19 THEN 'Dengue fever'
            WHEN 20 THEN 'Measles'
            WHEN 21 THEN 'Chickenpox'
            WHEN 22 THEN 'Tuberculosis'
            WHEN 23 THEN 'Rheumatism'
            WHEN 24 THEN 'Eczema'
            WHEN 25 THEN 'Psoriasis'
            WHEN 26 THEN 'Meningitis'
            WHEN 27 THEN 'Hepatitis'
            WHEN 28 THEN 'Cancer'
            WHEN 29 THEN 'Stroke'
            WHEN 30 THEN 'Common Cold'
            ELSE 'Unknown'
        END
    WHEN "BED_7" IS NOT NULL THEN
        CASE floor(random()*31)::int
            WHEN 0 THEN 'Fever'
            WHEN 1 THEN 'Influenza'
            WHEN 2 THEN 'Pneumonia'
            WHEN 3 THEN 'Appendicitis'
            WHEN 4 THEN 'Asthma'
            WHEN 5 THEN 'Diabetes'
            WHEN 6 THEN 'Hypertension'
            WHEN 7 THEN 'Arthritis'
            WHEN 8 THEN 'Migraine'
            WHEN 9 THEN 'COVID-19'
            WHEN 10 THEN 'Bronchitis'
            WHEN 11 THEN 'Gastritis'
            WHEN 12 THEN 'Ulcer'
            WHEN 13 THEN 'Kidney stones'
            WHEN 14 THEN 'Urinary tract infection'
            WHEN 15 THEN 'Conjunctivitis'
            WHEN 16 THEN 'Malaria'
            WHEN 17 THEN 'Cholera'
            WHEN 18 THEN 'Typhoid'
            WHEN 19 THEN 'Dengue fever'
            WHEN 20 THEN 'Measles'
            WHEN 21 THEN 'Chickenpox'
            WHEN 22 THEN 'Tuberculosis'
            WHEN 23 THEN 'Rheumatism'
            WHEN 24 THEN 'Eczema'
            WHEN 25 THEN 'Psoriasis'
            WHEN 26 THEN 'Meningitis'
            WHEN 27 THEN 'Hepatitis'
            WHEN 28 THEN 'Cancer'
            WHEN 29 THEN 'Stroke'
            WHEN 30 THEN 'Common Cold'
            ELSE 'Unknown'
        END
    WHEN "BED_8" IS NOT NULL THEN
        CASE floor(random()*31)::int
            WHEN 0 THEN 'Fever'
            WHEN 1 THEN 'Influenza'
            WHEN 2 THEN 'Pneumonia'
            WHEN 3 THEN 'Appendicitis'
            WHEN 4 THEN 'Asthma'
            WHEN 5 THEN 'Diabetes'
            WHEN 6 THEN 'Hypertension'
            WHEN 7 THEN 'Arthritis'
            WHEN 8 THEN 'Migraine'
            WHEN 9 THEN 'COVID-19'
            WHEN 10 THEN 'Bronchitis'
            WHEN 11 THEN 'Gastritis'
            WHEN 12 THEN 'Ulcer'
            WHEN 13 THEN 'Kidney stones'
            WHEN 14 THEN 'Urinary tract infection'
            WHEN 15 THEN 'Conjunctivitis'
            WHEN 16 THEN 'Malaria'
            WHEN 17 THEN 'Cholera'
            WHEN 18 THEN 'Typhoid'
            WHEN 19 THEN 'Dengue fever'
            WHEN 20 THEN 'Measles'
            WHEN 21 THEN 'Chickenpox'
            WHEN 22 THEN 'Tuberculosis'
            WHEN 23 THEN 'Rheumatism'
            WHEN 24 THEN 'Eczema'
            WHEN 25 THEN 'Psoriasis'
            WHEN 26 THEN 'Meningitis'
            WHEN 27 THEN 'Hepatitis'
            WHEN 28 THEN 'Cancer'
            WHEN 29 THEN 'Stroke'
            WHEN 30 THEN 'Common Cold'
            ELSE 'Unknown'
        END
    WHEN "BED_9" IS NOT NULL THEN
        CASE floor(random()*31)::int
            WHEN 0 THEN 'Fever'
            WHEN 1 THEN 'Influenza'
            WHEN 2 THEN 'Pneumonia'
            WHEN 3 THEN 'Appendicitis'
            WHEN 4 THEN 'Asthma'
            WHEN 5 THEN 'Diabetes'
            WHEN 6 THEN 'Hypertension'
            WHEN 7 THEN 'Arthritis'
            WHEN 8 THEN 'Migraine'
            WHEN 9 THEN 'COVID-19'
            WHEN 10 THEN 'Bronchitis'
            WHEN 11 THEN 'Gastritis'
            WHEN 12 THEN 'Ulcer'
            WHEN 13 THEN 'Kidney stones'
            WHEN 14 THEN 'Urinary tract infection'
            WHEN 15 THEN 'Conjunctivitis'
            WHEN 16 THEN 'Malaria'
            WHEN 17 THEN 'Cholera'
            WHEN 18 THEN 'Typhoid'
            WHEN 19 THEN 'Dengue fever'
            WHEN 20 THEN 'Measles'
            WHEN 21 THEN 'Chickenpox'
            WHEN 22 THEN 'Tuberculosis'
            WHEN 23 THEN 'Rheumatism'
            WHEN 24 THEN 'Eczema'
            WHEN 25 THEN 'Psoriasis'
            WHEN 26 THEN 'Meningitis'
            WHEN 27 THEN 'Hepatitis'
            WHEN 28 THEN 'Cancer'
            WHEN 29 THEN 'Stroke'
            WHEN 30 THEN 'Common Cold'
            ELSE 'Unknown'
        END
    WHEN "BED_10" IS NOT NULL THEN
        CASE floor(random()*31)::int
            WHEN 0 THEN 'Fever'
            WHEN 1 THEN 'Influenza'
            WHEN 2 THEN 'Pneumonia'
            WHEN 3 THEN 'Appendicitis'
            WHEN 4 THEN 'Asthma'
            WHEN 5 THEN 'Diabetes'
            WHEN 6 THEN 'Hypertension'
            WHEN 7 THEN 'Arthritis'
            WHEN 8 THEN 'Migraine'
            WHEN 9 THEN 'COVID-19'
            WHEN 10 THEN 'Bronchitis'
            WHEN 11 THEN 'Gastritis'
            WHEN 12 THEN 'Ulcer'
            WHEN 13 THEN 'Kidney stones'
            WHEN 14 THEN 'Urinary tract infection'
            WHEN 15 THEN 'Conjunctivitis'
            WHEN 16 THEN 'Malaria'
            WHEN 17 THEN 'Cholera'
            WHEN 18 THEN 'Typhoid'
            WHEN 19 THEN 'Dengue fever'
            WHEN 20 THEN 'Measles'
            WHEN 21 THEN 'Chickenpox'
            WHEN 22 THEN 'Tuberculosis'
            WHEN 23 THEN 'Rheumatism'
            WHEN 24 THEN 'Eczema'
            WHEN 25 THEN 'Psoriasis'
            WHEN 26 THEN 'Meningitis'
            WHEN 27 THEN 'Hepatitis'
            WHEN 28 THEN 'Cancer'
            WHEN 29 THEN 'Stroke'
            WHEN 30 THEN 'Common Cold'
            ELSE 'Unknown'
        END
        
    ELSE NULL
END;
