CREATE DATABASE HMS;

CREATE TABLE DOCTOR (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    DATE_BIRTH DATE,
    DEPARTMENT_ID INT,
    CONTACT_NO VARCHAR(20),
    SALARY DECIMAL(10, 2),
    GENDER CHAR(1)
);
